### ISSUE TITLE
User can flip over the main tile

### ISSUE THREAD

**Issue by jayb0c** [jakeStoneDev/ajax-project#3]
- [x] There is a folded corner in the top right corner of the current weather tile
- [x] The user can hover over the corner and it should react with a change in style
- [x] When the user clicks this corner, the tile should flip to the back side
- [x] There is a folded corner on the back page as well
- [x] The user can click the top right to change back to the front of the tile

**Comment by jakeStoneDev** [comment]
## 💰 Motivation

There is more space on the back of the tile to save space and maintain a clean look

## 📐 Plan

Create an interactive page fold that allows the user to flip the white tile to it's back

## 🖼️ Wireframes
<img width="242" alt="Screen Shot 2021-10-18 at 8 06 09 PM" src="https://user-images.githubusercontent.com/80498184/137837063-4113ff40-8d25-494d-8c4c-110afef73465.png">
